name: License tests
on:
  workflow_dispatch:
  push:

jobs:
  license:
    runs-on: ubuntu-latest
    steps:
      - uses: openvoiceos/.github/.github/workflows/license_tests.yml@feat/shared_actions1
        with:
          branch: dev
          action_branch: feat/shared_actions1
          python_version: "3.10"
          locale_folder: locale
