name: License tests
on:
  workflow_dispatch:
  push:

jobs:
  license:
    uses: openvoiceos/.github/.github/workflows/license_tests.yml@feat/shared_actions1
    with:
      branch: dev
      action_branch: feat/shared_actions1
      system-deps: jq
      licenses-exclude: AGPL-3.0
      package-extras: test
      python-version: "3.10"
      packages-exclude: ovos-workshop
