name: Test Resources
on:
  workflow_dispatch:
  push:

jobs:
  test-resources:
    uses: openvoiceos/.github/.github/workflows/skill_test_resources.yml@feat/shared_actions1
    with:
      action_branch: feat/shared_actions1
      python_version: "3.10"
      system_deps: yq
      pip_packages: pytest-cov
      skill_id: newskill
      resource_testfile: test/test_resources.yaml
