name: Run Unit Tests
on:
  workflow_dispatch:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: openvoiceos/.github/.github/workflows/publish_alpha_release.yml@feat/shared_actions1
        with:
          # runner:
          # branch:
          action_branch: "feat/shared_actions1"
          system_deps: jq
          python_matrix: '[3.8, 3.9, "3.10", "3.11", "3.12"]'
          pip_packages: pytest
          install_extras: "test,dev" # Don't actually exist but that should be ok
          timeout_minutes: 1 # Test multiple
          test_location: test
          is_skill: true
          codecov: true
          append_coverage: true
          upload_coverage: true
